/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controlador.DAO_Estudiante;
import Modelo.Estudiante;
import java.util.LinkedList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Genaro López
 */
public class PanelConsultarEstudiante extends javax.swing.JPanel {

    DAO_Estudiante DAOestudiante;

    /**
     * Creates new form PanelConsultarEstudiante
     */
    public PanelConsultarEstudiante() {
        initComponents();
        cargarEstudiantes();
    }

    /**
     * Carga en el jListEstudiantes los estudiantes en la base de datos.
     */
    public void cargarEstudiantes() {
        try {
            DAOestudiante = new DAO_Estudiante();
            DAOestudiante.conexion.conectar();
            LinkedList<Estudiante> estudiantes;
            estudiantes = DAOestudiante.consultarEstudiantes();
            DAOestudiante.conexion.cerrarConexion();
            jListEstudiantes.removeAll();
            DefaultListModel modelo = new DefaultListModel();
            for (Estudiante estudiante : estudiantes) {
                modelo.addElement(estudiante.getNombre().concat(" " + estudiante.getApellido()));
            }
            jListEstudiantes.setModel(modelo);
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    public void mostrarDatosEstudiante(Estudiante es) {
        String informacion = "Nombre:\t" + es.getNombre() + " " + es.getApellido() + "\n"
                + "Cédula:\t" + es.getCedula() + "\nTeléfono1:\t" + es.getTelefono1() + "\n"
                + "Teléfono2:\t" + es.getTelefono2() + "\n";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListEstudiantes = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setViewportView(jListEstudiantes);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(166, 187, 63));
        jLabel1.setText("Consultar Estudiante");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jListEstudiantes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
