package GUI;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Genaro
 */
public class PanelBanner extends javax.swing.JPanel {

    private ImageIcon fondo;

    /**
     * Creates new form PanelBanner
     */
    public PanelBanner() {
        initComponents();
        fondo = new ImageIcon(getClass().getResource("/recursos/banner2.png"));
    }

    @Override
    public void paintComponent(Graphics g) {
        g.drawImage(getFondo().getImage(), 0, 0, getSize().width, getSize().height, null);
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * @return the fondo
     */
    public ImageIcon getFondo() {
        return fondo;
    }

    /**
     * @param fondo the fondo to set
     */
    public void setFondo(ImageIcon fondo) {
        this.fondo = fondo;
    }
}
