/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controlador.DAO_Estudiante;
import Modelo.Estudiante;
import javax.swing.DefaultListModel;

/**
 *
 * @author Genaro López
 */
public class PanelConsultarEstudiante extends javax.swing.JPanel {

    DAO_Estudiante DAOestudiante;

    /**
     * Creates new form PanelConsultarEstudiante
     */
    public PanelConsultarEstudiante() {
        initComponents();
        this.setSize(555, 434);
        jComboBox1.setVisible(false);
        cargarEstudiantes();
    }

    /**
     * Carga en el jListEstudiantes los estudiantes en la base de datos.
     */
    public void cargarEstudiantes() {
        try {
            DAOestudiante = new DAO_Estudiante();
            DAOestudiante.conexion.conectar();
            DAOestudiante.consultarEstudiantes();
            DAOestudiante.conexion.cerrarConexion();
            jListEstudiantes.removeAll();
            DefaultListModel modelo = new DefaultListModel();
            for (Estudiante estudiante : DAOestudiante.estudiantes) {
                modelo.addElement(estudiante.getNombre().concat(" " + estudiante.getApellido()));
            }
            jListEstudiantes.setModel(modelo);
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    public String mostrarDatosEstudiante(Estudiante es) {
        String informacion = "\n   Nombre:\t   " + es.getNombre() + " " + es.getApellido() + "\n   "
                + "Cédula:\t   " + es.getCedula() + "\n   Teléfono1:\t   " + es.getTelefono1() + "\n   "
                + "Teléfono2:\t   " + es.getTelefono2() + "\n   e-mail:\t   " + es.getEmail() + "\n   "
                + "Username:\t   " + es.getNombreDeUsuario() + "\n   Dirección:\t   " + es.getDireccion()
                + "\n   Realiza\n   monitoreo:\t   " + ((es.isEsMonitoreo()) ? "si" : "no") + "\n   "
                + "Realiza\n   investigación:\t   " + ((es.isEsInvestigacion()) ? "si" : "no") + "\n   "
                + "Está activo:\t   " + ((es.isActivado()) ? "si" : "no") + "\n   "
                + "Departamento\n   de:\t   " + es.nombreSeccion + "\n   "
                + "Activo desde:\t   " + es.getFechaCreado() + "\n   "
                + "Activo hasta:\t   " + es.getFechaSalida() + "\n";
        return informacion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListEstudiantes = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaInformacion = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jListEstudiantes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListEstudiantes.setAlignmentX(1.0F);
        jListEstudiantes.setAlignmentY(1.0F);
        jListEstudiantes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListEstudiantesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListEstudiantes);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(166, 187, 63));
        jLabel1.setText("Consultar Estudiante");

        jTextAreaInformacion.setEditable(false);
        jTextAreaInformacion.setColumns(20);
        jTextAreaInformacion.setRows(5);
        jTextAreaInformacion.setBorder(null);
        jScrollPane2.setViewportView(jTextAreaInformacion);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(166, 187, 63));
        jButton1.setText("Ver resumen de actividades");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jListEstudiantesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListEstudiantesValueChanged
        try {
            String informacion = mostrarDatosEstudiante(DAOestudiante.estudiantes.get(jListEstudiantes.getSelectedIndex()));
            jTextAreaInformacion.setText(informacion);
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_jListEstudiantesValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jListEstudiantes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaInformacion;
    // End of variables declaration//GEN-END:variables
}
