package GUI;

import Controlador.DAO_Seccion;
import Modelo.Seccion;
import java.util.LinkedList;

/**
 *
 * @author Genaro López
 */
public class PanelCrearEstudiante extends javax.swing.JPanel {

    /**
     * Creates new form PanelCrearEstudiante
     */
    public PanelCrearEstudiante() {
        initComponents();
        cargarSeccionesCombo();
    }

    public void cargarSeccionesCombo() {
        DAO_Seccion seccion = new DAO_Seccion();
        LinkedList<Seccion> secciones = seccion.consultarSecciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nom = new javax.swing.JLabel();
        ape = new javax.swing.JLabel();
        ced = new javax.swing.JLabel();
        tel1 = new javax.swing.JLabel();
        tel2 = new javax.swing.JLabel();
        sec = new javax.swing.JLabel();
        con = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldApe = new javax.swing.JTextField();
        jTextFieldCed = new javax.swing.JTextField();
        jTextFieldTel1 = new javax.swing.JTextField();
        jTextFieldTel2 = new javax.swing.JTextField();
        jComboBoxSec = new javax.swing.JComboBox();
        jTextFieldCon = new javax.swing.JTextField();
        jRadioButtonMon = new javax.swing.JRadioButton();
        jRadioButtonInv = new javax.swing.JRadioButton();
        panelBanner1 = new GUI.PanelBanner();
        confirmar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        nom.setText("Nombre");

        ape.setText("Apelido");

        ced.setText("Cédula");

        tel1.setText("Teléfono");

        tel2.setText("Teléfono 2");

        sec.setText("Sección ");

        con.setText("Contraseña");

        jRadioButtonMon.setText("Monitoreo");
        jRadioButtonMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMonActionPerformed(evt);
            }
        });

        jRadioButtonInv.setText("Investigación");

        javax.swing.GroupLayout panelBanner1Layout = new javax.swing.GroupLayout(panelBanner1);
        panelBanner1.setLayout(panelBanner1Layout);
        panelBanner1Layout.setHorizontalGroup(
            panelBanner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelBanner1Layout.setVerticalGroup(
            panelBanner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        confirmar.setText("Confirmar");

        cancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBanner1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(confirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nom)
                                    .addComponent(ape)
                                    .addComponent(ced)
                                    .addComponent(tel1)
                                    .addComponent(tel2)
                                    .addComponent(sec)
                                    .addComponent(con))
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jRadioButtonInv)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNom)
                            .addComponent(jTextFieldApe)
                            .addComponent(jTextFieldCed)
                            .addComponent(jTextFieldTel1)
                            .addComponent(jTextFieldTel2)
                            .addComponent(jTextFieldCon)
                            .addComponent(jComboBoxSec, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jRadioButtonMon)))))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelBanner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ape)
                    .addComponent(jTextFieldApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ced)
                    .addComponent(jTextFieldCed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tel1)
                    .addComponent(jTextFieldTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tel2)
                    .addComponent(jTextFieldTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sec)
                    .addComponent(jComboBoxSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(con)
                    .addComponent(jTextFieldCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMon)
                    .addComponent(jRadioButtonInv))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmar)
                    .addComponent(cancelar))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ape;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel ced;
    private javax.swing.JLabel con;
    private javax.swing.JButton confirmar;
    private javax.swing.JComboBox jComboBoxSec;
    private javax.swing.JRadioButton jRadioButtonInv;
    private javax.swing.JRadioButton jRadioButtonMon;
    private javax.swing.JTextField jTextFieldApe;
    private javax.swing.JTextField jTextFieldCed;
    private javax.swing.JTextField jTextFieldCon;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldTel1;
    private javax.swing.JTextField jTextFieldTel2;
    private javax.swing.JLabel nom;
    private GUI.PanelBanner panelBanner1;
    private javax.swing.JLabel sec;
    private javax.swing.JLabel tel1;
    private javax.swing.JLabel tel2;
    // End of variables declaration//GEN-END:variables
}
