/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controlador.DAO_Turno;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Genaro López
 */
public class PanelEditarTurnos extends javax.swing.JPanel {

    DAO_Turno turno;

    /**
     * Creates new form PanelEditarTurnos
     */
    public PanelEditarTurnos() {
        initComponents();
        this.setSize(552, 411);
        turno = new DAO_Turno();
        cargarTurnosTabla(true, tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        modificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(166, 187, 63));
        jLabel3.setText("Turnos incompletos");

        modificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        modificar.setForeground(new java.awt.Color(166, 187, 63));
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Fecha Inicio", "Hora Fin", "Duración (min)", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(modificar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modificar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        actualizarTurnosDesdeJTable();
        turno.actualizarTurnosBD();
        cargarTurnosTabla(true, tabla);
    }//GEN-LAST:event_modificarActionPerformed

    public void actualizarTurnosDesdeJTable() {
      
        for (int i = 0; i < tabla.getRowCount(); i++) {
            if (tabla.getValueAt(i, 3) != null) {
                if (tabla.getValueAt(i, 4) != null) {
                    turno.turnos.get(i).setDuración((int) tabla.getValueAt(i, 3));
                    turno.turnos.get(i).setDescripcion((String) tabla.getValueAt(i, 4));
                    System.out.println(turno.turnos.get(i).getDuración());
                    System.out.println(turno.turnos.get(i).getDescripcion());
                }
            } else {
//                JOptionPane.showMessageDialog(this, "", TOOL_TIP_TEXT_KEY, WIDTH);
            }
        }
    }

    /**
     * Llama los métodos que cargan los turnos incompletos en la tabla.
     *
     * @param sentenciaCompleta
     * @param tabla
     */
    public void cargarTurnosTabla(boolean sentenciaCompleta, JTable tabla) {

        turno.consultarTurnos(sentenciaCompleta);
        turno.cargarTurnosTabla(sentenciaCompleta, tabla);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificar;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
